#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# overnight.sh — run a batch of SRS x arm experiments unattended on Minsky.
#
#   tmux new -s overnight
#   ./scripts/minsky/overnight.sh data/srs/Human.xml data/srs/dineout_srs.xml ...
#   # Ctrl-B then D to detach; reattach with: tmux attach -t overnight
#
# Defaults to every SRS in data/srs/ if you name none.
#
# Designed for the things that go wrong while you sleep:
#   * the 8 h walltime kills the server mid-batch  -> resubmits and waits, then continues
#   * one run hangs                                -> per-run timeout, moves on
#   * one run crashes                              -> logged, batch continues
#   * you want partial results                     -> each run writes as it finishes
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail                      # NOT -e: a failing run must not end the batch
cd "$(dirname "$0")/../.."
MINSKY_DIR="$(cd "$(dirname "$0")" && pwd)"

MODEL_KEY="${MODEL_KEY:-qwen-coder}"
ARMS="${ARMS:-deterministic deepagent}"
STRATEGY="${STRATEGY:-mot}"
LANGUAGE="${LANGUAGE:-python}"
RUN_TIMEOUT="${RUN_TIMEOUT:-4200}"      # 70 min per run
PIPELINE_FLAGS="${PIPELINE_FLAGS:---prove --certify}"

STAMP=$(date +%Y%m%d-%H%M%S)
RESULTS="${RESULTS:-results/new_feature_2026-08-26/raw_results/batch-$STAMP}"
mkdir -p "$RESULTS"
SUMMARY="$RESULTS/summary.tsv"
printf 'srs\tarm\tstatus\tseconds\toutput\n' > "$SUMMARY"

SRS_LIST=("$@")
[ ${#SRS_LIST[@]} -gt 0 ] || SRS_LIST=(data/srs/*.xml)

log() { echo "[$(date '+%F %T')] $*" | tee -a "$RESULTS/batch.log"; }

# Dafny is needed for --prove; warn loudly ONCE rather than silently losing the proof track
# on every run, which is the whole point of the night.
if ! command -v dafny >/dev/null; then
  log "WARNING: dafny not on PATH — the proof tier will be skipped in every run."
  log "         export PATH=\"\$HOME/tools/dafny:\$PATH\" and restart if you want proofs."
fi

server_alive() {
  local base; base=$(sed -n 's|^LLM_BASE_URL=||p' .env 2>/dev/null)
  [ -n "$base" ] && curl -sf --max-time 8 "$base/models" >/dev/null 2>&1
}

# Bring a server up and block until it answers. Returns 1 if it never does.
ensure_server() {
  server_alive && return 0
  log "no live server — submitting a new one (MODEL_KEY=$MODEL_KEY)"
  local job
  job=$(sbatch --parsable \
        --export=ALL,MODEL_KEY="$MODEL_KEY",CLEANROOM_MINSKY_DIR="$MINSKY_DIR" \
        "$MINSKY_DIR/serve_vllm.sbatch") || { log "sbatch failed"; return 1; }
  log "  job $job submitted; waiting for it to serve"
  local state
  for _ in $(seq 1 240); do             # up to 2 h (queue + weight load)
    state=$(squeue -h -j "$job" -o %T 2>/dev/null)
    if [ -z "$state" ]; then
      log "  job $job left the queue — see cleanroom-vllm_$job.out"; return 1
    fi
    if [ "$state" = "RUNNING" ] && [ -f "$HOME/.cleanroom-vllm/jobs/$job.json" ]; then
      local node port model
      node=$(sed -n 's/.*"node"[^"]*"\([^"]*\)".*/\1/p' "$HOME/.cleanroom-vllm/jobs/$job.json")
      port=$(sed -n 's/.*"port"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$HOME/.cleanroom-vllm/jobs/$job.json")
      model=$(sed -n 's/.*"model"[^"]*"\([^"]*\)".*/\1/p' "$HOME/.cleanroom-vllm/jobs/$job.json")
      if curl -sf --max-time 5 "http://$node:$port/v1/models" >/dev/null 2>&1; then
        { echo "# regenerated by overnight.sh — job $job on $node"
          echo "LLM_BASE_URL=http://$node:$port/v1"
          echo "LLM_MODEL=$model"
          echo "LLM_API_KEY=EMPTY"
          [ "$MODEL_KEY" = "r1-distill" ] && echo "CLEANROOM_LLM_TEMPERATURE=0.6"
        } > .env
        log "  server up on $node:$port ($model)"
        return 0
      fi
    fi
    sleep 30
  done
  log "  server never answered"; return 1
}

log "batch $STAMP — ${#SRS_LIST[@]} SRS x $(echo $ARMS | wc -w) arm(s)"
log "results -> $RESULTS"

for srs in "${SRS_LIST[@]}"; do
  [ -f "$srs" ] || { log "SKIP missing $srs"; continue; }
  stem=$(basename "$srs" .xml)
  for arm in $ARMS; do
    out="$RESULTS/$stem/$arm"
    if [ -f "$out/.done" ]; then
      log "SKIP $stem/$arm (already complete)"      # makes the batch resumable
      continue
    fi
    mkdir -p "$out"

    if ! ensure_server; then
      log "FATAL: cannot get a server; stopping. Completed runs are kept in $RESULTS"
      exit 1
    fi

    flags=($PIPELINE_FLAGS)
    [ "$arm" = "deepagent" ] && flags+=(--gen-driver deepagent --repair-driver deepagent)

    log "RUN  $stem / $arm"
    start=$SECONDS
    timeout "$RUN_TIMEOUT" uv run python run_pipeline.py "$srs" \
      --language "$LANGUAGE" --prompt-strategy "$STRATEGY" \
      "${flags[@]}" --output-dir "$out" > "$out/run.log" 2>&1
    rc=$?
    elapsed=$((SECONDS - start))

    case $rc in
      0)   status=ok;      touch "$out/.done" ;;
      124) status=timeout ;;
      *)   status="failed($rc)" ;;
    esac
    log "DONE $stem / $arm -> $status in ${elapsed}s"
    printf '%s\t%s\t%s\t%s\t%s\n' "$stem" "$arm" "$status" "$elapsed" "$out" >> "$SUMMARY"
  done
done

log "batch finished"
column -t "$SUMMARY" 2>/dev/null || cat "$SUMMARY"
