#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# run_all.sh — one command, run ENTIRELY ON THE MINSKY LOGIN NODE.
#
#   ./scripts/minsky/run_all.sh                      # smallest SRS, quick smoke test
#   ./scripts/minsky/run_all.sh data/srs/dineout_srs.xml java
#
# Submits the vLLM job, waits until the server actually answers, writes .env
# pointing straight at the GPU node, runs the pipeline, then frees the GPU.
# No SSH tunnel and no VPN needed — the login node reaches the compute node directly.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/../.."

SRS="${1:-data/srs/Human.xml}"
LANG_="${2:-python}"
MODEL_KEY="${MODEL_KEY:-qwen-coder}"
# Where the experiment lands. RESULTS_DIR holds BOTH the per-run artifact tree and the
# aggregated CSV; run artifacts use the matrix layout <lang>/<srs>/<model> that
# scripts/collect_metrics.py derives language/srs/model from, so repeated runs accumulate
# as separate rows in one CSV instead of overwriting each other.
RESULTS_DIR="${RESULTS_DIR:-results/minsky_qwen3_2026-09-03}"
CSV="${CSV:-$RESULTS_DIR/metrics.csv}"
KEEP_SERVER="${KEEP_SERVER:-0}"    # 1 = leave the job running after the pipeline finishes

command -v uv >/dev/null || { echo "ERROR: uv not found. Install it once with:"; \
  echo "    curl -LsSf https://astral.sh/uv/install.sh | sh"; exit 1; }

echo "── submitting vLLM job (MODEL_KEY=$MODEL_KEY)"
# CLEANROOM_MINSKY_DIR is exported so the job can find models.conf regardless of where
# Slurm stages the script (it copies it into /var/spool/slurmd/job<N>/).
MINSKY_DIR="$(cd "$(dirname "$0")" && pwd)"
JOB=$(sbatch --parsable \
  --export=ALL,MODEL_KEY="$MODEL_KEY",CLEANROOM_MINSKY_DIR="$MINSKY_DIR" \
  "$MINSKY_DIR/serve_vllm.sbatch")
echo "   job $JOB"

cleanup() {
  if [ "$KEEP_SERVER" = "1" ]; then
    echo "── leaving job $JOB running (KEEP_SERVER=1). Free it with: scancel $JOB"
  else
    echo "── releasing GPU (scancel $JOB)"; scancel "$JOB" 2>/dev/null || true
  fi
}
trap cleanup EXIT

echo "── waiting for the GPU and for weights to load (first run downloads ~19 GB)"
STATE_FILE="$HOME/.cleanroom-vllm/jobs/$JOB.json"
for _ in $(seq 1 240); do          # up to 2 h
  ST=$(squeue -h -j "$JOB" -o %T 2>/dev/null || true)
  case "$ST" in
    "") echo "ERROR: job $JOB left the queue. Check cleanroom-vllm_$JOB.out"; exit 1 ;;
    PENDING) printf '\r   queued for a GPU…                    ' ;;
    RUNNING)
      if [ -f "$STATE_FILE" ]; then
        NODE=$(sed -n 's/.*"node"[^"]*"\([^"]*\)".*/\1/p' "$STATE_FILE")
        PORT=$(sed -n 's/.*"port"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$STATE_FILE")
        MODEL=$(sed -n 's/.*"model"[^"]*"\([^"]*\)".*/\1/p' "$STATE_FILE")
        if curl -sf --max-time 5 "http://${NODE}:${PORT}/v1/models" >/dev/null 2>&1; then
          printf '\r   server up on %s:%s        \n' "$NODE" "$PORT"; break
        fi
        printf '\r   on %s — loading weights…            ' "$NODE"
      fi ;;
  esac
  sleep 30
done

[ -n "${NODE:-}" ] || { echo "ERROR: server never answered. See cleanroom-vllm_$JOB.out"; exit 1; }

# Only the R1 distills need this: they loop at temperature 0. Qwen3 measurably does not,
# and raising it randomises the deterministic generation agents. See tunnel.sh.
TEMP=""; case "$MODEL_KEY" in r1-distill) TEMP=0.6 ;; esac

cat > .env <<ENVEOF
# Generated by scripts/minsky/run_all.sh — job $JOB, node $NODE
LLM_BASE_URL=http://${NODE}:${PORT}/v1
LLM_MODEL=${MODEL}
LLM_API_KEY=EMPTY
ENVEOF
if [ -n "$TEMP" ]; then echo "CLEANROOM_LLM_TEMPERATURE=${TEMP}" >> .env; fi

# Matrix cell: <results>/outputs/<language>/<srs_stem>/<model_safe>/ — the layout
# collect_metrics.py reads the three identity columns out of. `/` and `.` are not safe in a
# path component, so the model id is flattened the same way the existing CSVs have it
# (Qwen/Qwen3-32B-AWQ -> Qwen_Qwen3-32B-AWQ).
SRS_STEM="$(basename "$SRS")"; SRS_STEM="${SRS_STEM%.*}"
MODEL_SAFE="$(printf '%s' "$MODEL" | tr '/.' '__')"
OUT="${OUT:-$RESULTS_DIR/outputs/$LANG_/$SRS_STEM/$MODEL_SAFE}"

echo "── running pipeline: $SRS ($LANG_) → $OUT"
mkdir -p "$OUT"
# Don't let a mid-pipeline failure skip the collection: run_record.py still writes a run
# JSON for a failed/partial run, and that row is data too. Report the real status at the end.
PIPE_RC=0
uv run python run_pipeline.py "$SRS" \
  --language "$LANG_" \
  --prove --certify --output-dir "$OUT" || PIPE_RC=$?
[ "$PIPE_RC" -eq 0 ] || echo "!! pipeline exited $PIPE_RC — collecting whatever it recorded"

# Aggregate into the CSV. --append keeps rows from earlier runs (other SRS/model cells) and
# only updates this cell, so the file survives across the qwen3.8 / qwen-coder / r1-distill arms.
echo "── collecting metrics → $CSV"
uv run python scripts/collect_metrics.py --root "$RESULTS_DIR/outputs" --out "$CSV" --append

echo "── done."
echo "   artifacts : $OUT"
echo "   metrics   : $CSV"
exit "$PIPE_RC"
