#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# run_all.sh — one command, run ENTIRELY ON THE MINSKY LOGIN NODE.
#
#   ./scripts/minsky/run_all.sh                      # smallest SRS, quick smoke test
#   ./scripts/minsky/run_all.sh data/srs/dineout_srs.xml java
#
# Submits the vLLM job, waits until the server actually answers, writes .env
# pointing straight at the GPU node, runs the pipeline, then frees the GPU.
# No SSH tunnel and no VPN needed — the login node reaches the compute node directly.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/../.."

SRS="${1:-data/srs/Human.xml}"
LANG_="${2:-python}"
STRATEGY="${STRATEGY:-mot}"
MODEL_KEY="${MODEL_KEY:-qwen-coder}"
OUT="${OUT:-results/new_feature_2026-08-26/raw_results/$(date +%Y%m%d-%H%M%S)}"
KEEP_SERVER="${KEEP_SERVER:-0}"    # 1 = leave the job running after the pipeline finishes

command -v uv >/dev/null || { echo "ERROR: uv not found. Install it once with:"; \
  echo "    curl -LsSf https://astral.sh/uv/install.sh | sh"; exit 1; }

echo "── submitting vLLM job (MODEL_KEY=$MODEL_KEY)"
JOB=$(sbatch --parsable --export=ALL,MODEL_KEY="$MODEL_KEY" scripts/minsky/serve_vllm.sbatch)
echo "   job $JOB"

cleanup() {
  if [ "$KEEP_SERVER" = "1" ]; then
    echo "── leaving job $JOB running (KEEP_SERVER=1). Free it with: scancel $JOB"
  else
    echo "── releasing GPU (scancel $JOB)"; scancel "$JOB" 2>/dev/null || true
  fi
}
trap cleanup EXIT

echo "── waiting for the GPU and for weights to load (first run downloads ~19 GB)"
STATE_FILE="$HOME/.cleanroom-vllm/jobs/$JOB.json"
for _ in $(seq 1 240); do          # up to 2 h
  ST=$(squeue -h -j "$JOB" -o %T 2>/dev/null || true)
  case "$ST" in
    "") echo "ERROR: job $JOB left the queue. Check cleanroom-vllm_$JOB.out"; exit 1 ;;
    PENDING) printf '\r   queued for a GPU…                    ' ;;
    RUNNING)
      if [ -f "$STATE_FILE" ]; then
        NODE=$(sed -n 's/.*"node"[^"]*"\([^"]*\)".*/\1/p' "$STATE_FILE")
        PORT=$(sed -n 's/.*"port"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$STATE_FILE")
        MODEL=$(sed -n 's/.*"model"[^"]*"\([^"]*\)".*/\1/p' "$STATE_FILE")
        if curl -sf --max-time 5 "http://${NODE}:${PORT}/v1/models" >/dev/null 2>&1; then
          printf '\r   server up on %s:%s        \n' "$NODE" "$PORT"; break
        fi
        printf '\r   on %s — loading weights…            ' "$NODE"
      fi ;;
  esac
  sleep 30
done

[ -n "${NODE:-}" ] || { echo "ERROR: server never answered. See cleanroom-vllm_$JOB.out"; exit 1; }

cat > .env <<ENVEOF
# Generated by scripts/minsky/run_all.sh — job $JOB, node $NODE
LLM_BASE_URL=http://${NODE}:${PORT}/v1
LLM_MODEL=${MODEL}
LLM_API_KEY=EMPTY
ENVEOF

echo "── running pipeline: $SRS ($LANG_, $STRATEGY) → $OUT"
mkdir -p "$OUT"
uv run python run_pipeline.py "$SRS" \
  --language "$LANG_" --prompt-strategy "$STRATEGY" \
  --prove --certify --output-dir "$OUT"

echo "── done. Artifacts in $OUT"
