#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# tunnel.sh — find a running vLLM job on Minsky, tunnel to it, write .env.
# Run from your LAPTOP.
#
#   MINSKY_USER=your-netid ./scripts/minsky/tunnel.sh                # only job running
#   MINSKY_USER=your-netid ./scripts/minsky/tunnel.sh qwen-coder     # pick by model key
#   MINSKY_USER=your-netid ./scripts/minsky/tunnel.sh qwen3
#
# Holds the tunnel in the foreground; Ctrl-C closes it. Run the pipeline in a
# second terminal while this stays up.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail
cd "$(dirname "$0")/../.."

LOGIN="${MINSKY_LOGIN:-minsky.cs.txstate.edu}"
USER_ID="${MINSKY_USER:?set MINSKY_USER=your-netid}"
LOCAL_PORT="${LOCAL_PORT:-8000}"
WANT_KEY="${1:-}"
SSH="ssh ${USER_ID}@${LOGIN}"

echo "── querying ${USER_ID}@${LOGIN} for running servers"
# Emit one tab-separated row per registered job, keeping only those Slurm still
# reports as RUNNING (a killed job can leave its state file behind).
ROWS=$($SSH 'bash -s' <<'REMOTE'
shopt -s nullglob
for f in "$HOME"/.cleanroom-vllm/jobs/*.json; do
  jid=$(sed -n 's/.*"job_id"[^"]*"\([^"]*\)".*/\1/p' "$f")
  key=$(sed -n 's/.*"key"[^"]*"\([^"]*\)".*/\1/p' "$f")
  node=$(sed -n 's/.*"node"[^"]*"\([^"]*\)".*/\1/p' "$f")
  port=$(sed -n 's/.*"port"[[:space:]]*:[[:space:]]*\([0-9]*\).*/\1/p' "$f")
  model=$(sed -n 's/.*"model"[^"]*"\([^"]*\)".*/\1/p' "$f")
  state=$(squeue -h -j "$jid" -o %T 2>/dev/null | head -1)
  [ "$state" = "RUNNING" ] || continue
  printf '%s\t%s\t%s\t%s\t%s\n' "$jid" "$key" "$node" "$port" "$model"
done
REMOTE
)

[ -n "${ROWS//[[:space:]]/}" ] || {
  echo "ERROR: no running vLLM server found. On Minsky:"
  echo "    sbatch --gres=gpu:2 --export=ALL,MODEL_KEY=qwen-coder scripts/minsky/serve_vllm.sbatch"
  echo "    squeue -u \$USER      # wait for ST=R, then tail the .out for 'Uvicorn running'"
  exit 1; }

[ -n "$WANT_KEY" ] && ROWS=$(printf '%s\n' "$ROWS" | awk -F'\t' -v k="$WANT_KEY" '$2==k')
[ -n "${ROWS//[[:space:]]/}" ] || { echo "ERROR: no running server with key '$WANT_KEY'"; exit 1; }

COUNT=$(printf '%s\n' "$ROWS" | grep -c .)
if [ "$COUNT" -gt 1 ]; then
  echo "Several servers are running — pass one of these keys as an argument:"
  printf '%s\n' "$ROWS" | awk -F'\t' '{printf "    %-12s job %-10s %s:%s  (%s)\n",$2,$1,$3,$4,$5}'
  exit 1
fi

IFS=$'\t' read -r JOB KEY NODE PORT MODEL <<<"$(printf '%s' "$ROWS" | head -1)"
echo "   job $JOB  [$KEY]  →  ${NODE}:${PORT}"
echo "   model $MODEL"

# The R1 distills degenerate into repetition at temperature 0, so they need ~0.6.
# Qwen3 does NOT: measured on Qwen3-32B-AWQ, temperature 0 finishes cleanly (82% distinct
# lines over a long generation), while 0.6 spent a whole 4000-token budget inside the
# thinking block and returned EMPTY content. Raising it also randomises the generation
# agents, which all ask for 0.0 deliberately — the same task then submits on one run and
# stops after three turns on the next. Leave qwen3 at the deterministic default.
TEMP=""; case "$KEY" in r1-distill) TEMP=0.6 ;; esac

{
  echo "# Generated by scripts/minsky/tunnel.sh on $(date -Is)"
  echo "# Minsky job $JOB [$KEY] on node $NODE — regenerate after every sbatch."
  echo "LLM_BASE_URL=http://localhost:${LOCAL_PORT}/v1"
  echo "LLM_MODEL=${MODEL}"
  echo "LLM_API_KEY=EMPTY"
  if [ -n "$TEMP" ]; then echo "CLEANROOM_LLM_TEMPERATURE=${TEMP}   # reasoning model: loops at temperature 0"; fi
} > .env
echo "── wrote .env"; sed 's/^/     /' .env

echo "── tunnel localhost:${LOCAL_PORT} → ${NODE}:${PORT}   (Ctrl-C to close)"
echo "   verify:  curl -s localhost:${LOCAL_PORT}/v1/models | python3 -m json.tool"
exec ssh -N -L "${LOCAL_PORT}:${NODE}:${PORT}" "${USER_ID}@${LOGIN}"
